baseURL = "https://blog.fraq.io/"
languageCode = "en-us"
title = "fraq"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = ""
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
[[menu.main]]
    name = "Recommended Reading"
    url = "/recommended-reading/"
    weight = 5
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    siteURL = "https://blog.fraq.io"
    description = "Where infrastructure goes to cry"
    footer = "This work by [Bren Briggs](https://blog.fraq.io/) is licensed under [CC BY-NC-SA 4.0CC](https://creativecommons.org/licenses/by-nc-sa/4.0/) "
    custom_css = ["css/theme-override.css"]
